language: python
python:
    - "3.6"
services:
    - "postgresql"
install:
    - "pip install pep8"
    - "pip install -r req.txt"
before_script:
    - "psql -c 'create database travis_ci_test;' -U postgres"
    - "pep8 --exclude=migrations,templates,settings.py ."
script:
    - "python manage.py test"
