language: python
python:
  - "3.5"
  # - "3.5-dev"  # 3.5 development branch
  - "3.6"
  - "3.7-dev"  # 3.7 development branch
  - "nightly"
install:
  - pip install -r req.txt
services:
  - postgresql
before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
addons:
#  postgresql: "9.4"
#  postgresql: "9.6"
  postgresql: "10"