language: python
python:
    - "3.6"
services:
    - "postgresql"
before_script:
    - "psql -c 'create database travis_ci_test;' -U postgres"
install:
    - "pip install -r req.txt"
script:
    - "python manage.py test"
