# Generated by Django 2.0.2 on 2018-03-05 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'verbose_name': 'Задачу', 'verbose_name_plural': 'Задачи'},
        ),
        migrations.AlterField(
            model_name='courses',
            name='price',
            field=models.IntegerField(verbose_name='Цена'),
        ),
    ]
