# Generated by Django 2.0.2 on 2018-03-14 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webinar', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientinfo',
            name='company',
        ),
        migrations.RemoveField(
            model_name='clientinfo',
            name='phone',
        ),
    ]
